// This file was autogenerated by D:\Web\_lib\google\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('../../../../WD/gui/form/Field.js', ['wd.gui.form.Field'], ['goog.dom'], false);
goog.addDependency('../../../../WD/gui/form/TextField.js', ['wd.gui.form.TextField'], ['wd.gui.form.Field'], false);
